iw: Update for Android Pie
net/if_ether.h has been removed in bionic, change back to
net/ethernet.h. And set -Wno-error to suppress the errors for
self-assignment, which failed like:

error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]

The installed path has also been updated to /vendor/xbin instead.

Change-Id: I07cc8caf56ac6b25d76c5bcfbc25d424c065a86f